apiVersion: v2
name: wraft
description: A Helm chart for Wraft application deployment with improved organization and maintainability
type: application
version: 0.1.3
appVersion: '1.0.0'
# Additional metadata
keywords:
  - wraft
  - application
  - deployment
home: https://github.com/wraft/wraft-helm
sources:
  - https://github.com/wraft/wraft-helm
maintainers:
  - name: Wraft Team
    email: wraftteam@wraft.co
annotations:
  artifacthub.io/changes: |
    - Added CONTRIBUTING.md with comprehensive guidelines for contributors
    - Improved validation script to work without requiring a Kubernetes cluster
  artifacthub.io/maintainers: |
    - name: Wraft Team
      email: wraftteam@wraft.co
  artifacthub.io/links: |
    - name: Changelog
      url: https://github.com/wraft/wraft-helm/blob/main/CHANGELOG.md
dependencies:
  - name: ingress-nginx
    version: 4.0.6 # Use the latest version available
    repository: https://kubernetes.github.io/ingress-nginx
