# Production environment specific values
global:
  environment: "prod"
  domain: "example.com"  # Replace with your actual domain

# Environment variables for substitution
env:
  POSTGRES_USER: "wraft_prod"
  POSTGRES_PASSWORD: ""  # Should be set via --set or external secrets management
  POSTGRES_DB: "wraft_production"
  DB_HOST: "wraft-db.production.svc.cluster.local"
  DB_PORT: "5432"
  MINIO_SERVICE_NAME: "wraft-minio"
  TYPESENSE_SERVICE_NAME: "wraft-typesense"
  NAMESPACE: "production"
  DOMAIN: "example.com"  # Replace with your actual domain

# Production-specific resource limits
frontend:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

backend:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi

# Database configuration
db:
  env:
    POSTGRES_USER: "wraft_prod"
    POSTGRES_PASSWORD: ""  # Should be set via --set or external secrets management
    POSTGRES_DB: "wraft_production"
  persistence:
    size: 20Gi
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# MinIO configuration
minio:
  persistence:
    size: 50Gi
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# Typesense configuration
typesense:
  persistence:
    size: 20Gi
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# Enable TLS for production
ingress:
  tlsEnabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

# Enable monitoring for production
monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
  logging:
    enabled: true

# Enable backups for production
backup:
  enabled: true
  schedule: "0 0 * * *"
  retention: 30
  database:
    enabled: true
  objectStorage:
    enabled: true 