{{- if .Values.ingress.enabled }}
{{- $apiVersion := include "wraft.ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ if $.Values.global.domain }}{{ printf "%s.%s" .host $.Values.global.domain | quote }}{{ else }}{{ .host | quote }}{{ end }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  {{- if kindIs "string" .service.port }}
                  name: {{ .service.port }}
                  {{- else }}
                  number: {{ .service.port }}
                  {{- end }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .Release.Name }}-tls
  {{- end }}
{{- end }}