apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.security.createSecrets }}
  SECRET_KEY_BASE: {{ .Values.security.secretKeyBase | default (printf "%s-%s" .Release.Name "secret-key-base" | sha256sum | trunc 32) | b64enc | quote }}
  GUARDIAN_KEY: {{ .Values.security.guardianKey | default (printf "%s-%s" .Release.Name "guardian-key" | sha256sum | trunc 32) | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.db.enabled }}
  POSTGRES_USER: {{ .Values.db.env.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.env.POSTGRES_PASSWORD | default (printf "%s-%s" .Release.Name "postgres-password" | sha256sum | trunc 16) | b64enc | quote }}
  POSTGRES_DB: {{ .Values.db.env.POSTGRES_DB | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secrets
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.minio.enabled }}
  MINIO_ROOT_USER: {{ .Values.minio.env.MINIO_ROOT_USER | default (printf "%s-%s" .Release.Name "minio-user" | sha256sum | trunc 10) | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.env.MINIO_ROOT_PASSWORD | default (printf "%s-%s" .Release.Name "minio-password" | sha256sum | trunc 16) | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-typesense-secrets
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.typesense.enabled }}
  TYPESENSE_API_KEY: {{ .Values.typesense.env.TYPESENSE_API_KEY | default (printf "%s-%s" .Release.Name "typesense-key" | sha256sum | trunc 32) | b64enc | quote }}
  {{- end }}
