{{- if .Values.global.networkPolicy.enabled }}
{{- if .Values.db.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-network-policy
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.db.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.backend.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
{{- end }}

{{- if .Values.minio.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-minio-network-policy
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.minio.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.backend.name }}
    ports:
    {{- range .Values.minio.service.ports }}
    - protocol: TCP
      port: {{ .port }}
    {{- end }}
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    {{- range .Values.minio.service.ports }}
    - protocol: TCP
      port: {{ .port }}
    {{- end }}
{{- end }}

{{- if .Values.typesense.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-typesense-network-policy
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.typesense.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.backend.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.typesense.service.port }}
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.typesense.service.port }}
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend-network-policy
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backend.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-frontend-network-policy
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
{{- end }}

{{- if .Values.global.networkPolicy.defaultDenyEgress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny-egress
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress: []
{{- end }}

{{- if .Values.global.networkPolicy.defaultDenyIngress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny-ingress
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: []
{{- end }}
{{- end }} 