# services.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.frontend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.backend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.db.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.name }}
  labels:
    {{- include "wraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    {{- range .Values.minio.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ .Values.minio.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.typesense.service.name }}
spec:
  selector:
    app: {{ .Values.typesense.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.typesense.service.port }}
      targetPort: 8108
  type: {{ .Values.typesense.service.type }}
