name: Release Helm Chart

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
    tags:
      - 'wraft-*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      # 3. Package new charts
      - name: Package charts
        run: |
          mkdir -p .cr-release-packages
          helm package charts/* --destination .cr-release-packages

      # 4. Upload packaged charts as artifact (optional but good for debugging)
      - name: Upload packaged charts as artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-helm-charts
          path: .cr-release-packages/*.tgz

      # 5. Fetch existing charts from gh-pages safely (FIXED!)
      - name: Fetch existing charts from gh-pages
        run: |
          mkdir -p .cr-existing-packages
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "gh-pages branch exists, fetching existing charts..."
            git fetch origin gh-pages:gh-pages || true

            # Use a temporary worktree instead of checking out over current branch
            git worktree add /tmp/gh-pages gh-pages
            cp /tmp/gh-pages/*.tgz .cr-existing-packages/ 2>/dev/null || true
            cp /tmp/gh-pages/index.yaml .cr-existing-packages/ 2>/dev/null || true
            git worktree remove /tmp/gh-pages --force
          else
            echo "gh-pages branch doesn't exist yet, this will be the first release"
          fi

      # 6. Merge old and new charts
      - name: Merge existing and new charts
        run: |
          if [ -d .cr-existing-packages ] && [ "$(ls -A .cr-existing-packages/*.tgz 2>/dev/null)" ]; then
            echo "Copying existing charts..."
            cp .cr-existing-packages/*.tgz .cr-release-packages/ || true
          fi

      # 7. Generate index.yaml (merged)
      - name: Generate comprehensive index.yaml
        run: |
          helm repo index .cr-release-packages --url https://wraft.github.io/charts
          if [ -f .cr-existing-packages/index.yaml ]; then
            echo "Merging with existing index.yaml..."
            helm repo index .cr-release-packages --url https://wraft.github.io/charts --merge .cr-existing-packages/index.yaml
          fi
          touch .cr-release-packages/.nojekyll

      # 8. Push to GitHub Pages
      - name: Push to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .cr-release-packages
          keep_files: false

      # 9. Debugging step before release (just to confirm .tgz presence)
      - name: List packaged charts before release
        run: |
          echo "Charts that will be uploaded to the release:"
          ls -lh .cr-release-packages/*.tgz || echo "No charts found!"

      # 10. Create GitHub Release
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: .cr-release-packages/*.tgz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
