name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/wraft/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Helm CLI
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Update chart dependencies
      - name: Helm dependency update
        run: |
          echo "Running helm dependency update..."
          helm dependency update charts/wraft
          echo "Dependency update completed"

      # Debug: List charts directory contents
      - name: List charts directory
        run: |
          echo "Checking charts directory..."
          ls -la charts/wraft/ || echo 'No wraft directory'
          ls -la charts/wraft/charts/ || echo 'No charts directory'
          echo "Checking for Chart.lock..."
          cat charts/wraft/Chart.lock || echo 'No Chart.lock file'

      # Package the Helm chart
      - name: Package Helm chart
        run: |
          helm package charts/wraft --destination packaged

      # Generate Helm repo index.yaml
      - name: Create Helm repo index
        run: |
          helm repo index packaged --url https://wraft.github.io/charts

      # Publish packaged charts and index.yaml to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          publish_branch: gh-pages 