name: Release Helm Chart

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package charts
        run: |
          mkdir -p .cr-release-packages
          helm package charts/* --destination .cr-release-packages

      - name: Generate index.yaml
        run: |
          helm repo index .cr-release-packages --url https://wraft.github.io/charts

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .cr-release-packages
