name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/wraft/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Helm CLI
      - name: Set up Helm
        uses: azure/setup-helm@v3

      # Package the Helm chart
      - name: Package Helm chart
        run: |
          helm package charts/wraft --destination packaged

      # Generate Helm repo index.yaml
      - name: Create Helm repo index
        run: |
          helm repo index packaged --url https://wraft.github.io/wraft/

      # Publish packaged charts and index.yaml to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          publish_branch: gh-pages 