# Development environment specific values
global:
  environment: "dev"
  domain: "local"

# Environment variables for substitution
env:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "wraft_data"
  DB_HOST: "wraft-db.default.svc.cluster.local"
  DB_PORT: "5432"
  MINIO_SERVICE_NAME: "wraft-minio"
  TYPESENSE_SERVICE_NAME: "wraft-typesense"
  NAMESPACE: "default"
  DOMAIN: "local"

# Development-specific resource limits
frontend:
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

backend:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Database configuration
db:
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DB: "wraft_data"
  persistence:
    size: 1Gi

# MinIO configuration
minio:
  persistence:
    size: 1Gi

# Typesense configuration
typesense:
  persistence:
    size: 2Gi 